tests: Do not link libdconf_engine_test with libdconf_shm_dep
libdconf_mock already provides the same symbols and it causes multiple
definitions of dconf_shm_open().

This should never have worked, but some bugs in Meson made it work
somehow until 1.2.0rc2. It now fails to link:
```
/usr/bin/ld: tests/libdconf-mock.a.p/dconf-mock-shm.c.o: in function `dconf_shm_open':
./obj-x86_64-linux-gnu/../tests/dconf-mock-shm.c:34: multiple definition of `dconf_shm_open'; shm/libdconf-shm.a.p/dconf-shm.c.o:./obj-x86_64-linux-gnu/../shm/dconf-shm
.c:51: first defined here
```