Declare libdconf_service as a dependency
The dconf-service internal static library depends on generated files,
and we need to make sure that those files are available by the time we
build the tests that depend on them, as Meson builds everything in
parallel. If we don't do that, in cases of massive parallelised
builders, we will end up with errors like:

```
ccache cc -Itests/tests@@writer@exe -Itests -I../tests -I. -I../ -Itests/../service -I../tests/../service -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g '-DSYSCONFDIR="/etc"' -fno-common -Wmissing-prototypes -Wwrite-strings -O2 -g -m64 -mtune=generic '-DSRCDIR="/ostbuild/source/dconf/tests"'  -MD -MQ 'tests/tests@@writer@exe/writer.c.o' -MF 'tests/tests@@writer@exe/writer.c.o.d' -o 'tests/tests@@writer@exe/writer.c.o' -c ../tests/writer.c
../tests/writer.c:24:37: fatal error: service/dconf-generated.h: No such file or directory
```

Reviewed-by: nobody
Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>